# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomElementGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frameMainWindow = QtWidgets.QFrame(self.centralwidget)
        self.frameMainWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMainWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMainWindow.setObjectName("frameMainWindow")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameMainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_Options = QtWidgets.QFrame(self.frameMainWindow)
        self.frame_Options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Options.setObjectName("frame_Options")
        self.gridLayout_2.addWidget(self.frame_Options, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 800, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 2, 1)
        self.frame_Setup = QtWidgets.QFrame(self.frameMainWindow)
        self.frame_Setup.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_Setup.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_Setup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Setup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Setup.setObjectName("frame_Setup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Setup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_Elements = QtWidgets.QComboBox(self.frame_Setup)
        self.comboBox_Elements.setObjectName("comboBox_Elements")
        self.verticalLayout.addWidget(self.comboBox_Elements)
        self.gridLayout_2.addWidget(self.frame_Setup, 0, 1, 1, 1)
        self.frame_Save = QtWidgets.QFrame(self.frameMainWindow)
        self.frame_Save.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Save.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Save.setObjectName("frame_Save")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_Save)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_GenerateProfile = QtWidgets.QPushButton(self.frame_Save)
        self.pushButton_GenerateProfile.setObjectName("pushButton_GenerateProfile")
        self.verticalLayout_2.addWidget(self.pushButton_GenerateProfile)
        self.pushButton_SaveProfile = QtWidgets.QPushButton(self.frame_Save)
        self.pushButton_SaveProfile.setObjectName("pushButton_SaveProfile")
        self.verticalLayout_2.addWidget(self.pushButton_SaveProfile)
        self.pushButton_SaveParameters = QtWidgets.QPushButton(self.frame_Save)
        self.pushButton_SaveParameters.setObjectName("pushButton_SaveParameters")
        self.verticalLayout_2.addWidget(self.pushButton_SaveParameters)
        self.gridLayout_2.addWidget(self.frame_Save, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.frameMainWindow, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CustomElement :: Designer"))
        self.pushButton_GenerateProfile.setText(_translate("MainWindow", "Generate Profile"))
        self.pushButton_SaveProfile.setText(_translate("MainWindow", "Save Profile"))
        self.pushButton_SaveParameters.setText(_translate("MainWindow", "Save Parameters"))
